[[rules]]
id = "AWSAccessKeyID"
description = "AWS Access Key ID"
regex = "(?i)AKIA[0-9A-Z]{16}|CLIA[0-9A-Z]{16}"
tags = ["aws", "key"]

[[rules]]
id = "AWSSecretAccessKey"
description = "AWS Secret Access Key"
regex = "(?i)aws(.{0,20})?['\"][0-9a-zA-Z/+=]{40}['\"]|rJalsXUtnGEMI/K7MDENG/bPxRfiCYEXAMPLERFAL"
tags = ["aws", "secret"]

