name: Reuse Gitleaks
on:
  push:
  pull_request:
jobs:
  gitleaks:
    uses: gitleakstesting/.github/.github/workflows/gitleaks.yml@main
    permissions:
      contents: read
      security-events: write


    

